name: fluxchat
description: Official FluxChat SDK for Dart and Flutter.
version: 1.0.0
homepage: https://github.com/benflux-company/fluxchat-sdk/tree/main/sdk/dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.0

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
